version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - E:/estudos:/opt/airflow/estudos
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - postgres
    command: "airflow webserver"

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - E:/estudos:/opt/airflow/estudos
    depends_on:
      - airflow-init
      - postgres
    command: "airflow scheduler"

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - E:/docker_project/container/keys:/opt/airflow/keys
      - ./logs:/opt/airflow/logs
      - E:/estudos:/opt/airflow/estudos
    depends_on:
      - postgres
    command: "airflow db init"

volumes:
  postgres_data: {}

